type GraphQLError = { message: string };

export type AppSyncAuthMode = 'apiKey' | 'userPools';

function loadAppSyncConfigFromAwsExports(): {
  endpoint: string;
  apiKey: string;
} | null {
  try {
    // Avoid importing aws-exports (can confuse bundlers); just parse it.
    // File is generated by Amplify and contains the AppSync endpoint + API key.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('fs') as typeof import('fs');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require('path') as typeof import('path');

    const awsExportsPath = path.join(process.cwd(), 'src', 'aws-exports.js');
    if (!fs.existsSync(awsExportsPath)) return null;

    const contents = fs.readFileSync(awsExportsPath, 'utf8');

    const endpointMatch = contents.match(
      /"aws_appsync_graphqlEndpoint"\s*:\s*"([^"]+)"/
    );
    const apiKeyMatch = contents.match(/"aws_appsync_apiKey"\s*:\s*"([^"]+)"/);

    const endpoint = endpointMatch?.[1];
    const apiKey = apiKeyMatch?.[1];

    if (!endpoint || !apiKey) return null;
    return { endpoint, apiKey };
  } catch {
    return null;
  }
}

function getAppSyncConfig(): { endpoint: string; apiKey: string } | null {
  const endpoint =
    process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT ||
    process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT;
  const apiKey =
    process.env.AWS_APPSYNC_API_KEY ||
    process.env.NEXT_PUBLIC_AWS_APPSYNC_API_KEY;

  if (endpoint && apiKey) return { endpoint, apiKey };
  return loadAppSyncConfigFromAwsExports();
}

/**
 * Small helper to talk to the AppSync API using the generated endpoint + API key.
 * Kept server-side only by importing it from server components/actions.
 */
export async function requestGraphQL<T>(
  query: string,
  variables?: Record<string, unknown>,
  opts?: { authMode?: AppSyncAuthMode; jwt?: string }
): Promise<T> {
  const cfg = getAppSyncConfig();
  const authMode: AppSyncAuthMode = opts?.authMode ?? 'apiKey';

  if (!cfg?.endpoint) {
    throw new Error(
      'Missing AppSync configuration. Set AWS_APPSYNC_GRAPHQL_ENDPOINT (or NEXT_PUBLIC_* equivalents), or ensure src/aws-exports.js exists.'
    );
  }

  const headers: Record<string, string> = {
    'content-type': 'application/json',
  };

  if (authMode === 'apiKey') {
    if (!cfg.apiKey) {
      throw new Error(
        'Missing AppSync API key. Set AWS_APPSYNC_API_KEY (or NEXT_PUBLIC_* equivalents), or ensure src/aws-exports.js exists.'
      );
    }
    headers['x-api-key'] = cfg.apiKey;
  } else {
    const jwt = opts?.jwt;
    if (!jwt) {
      throw new Error(
        'Missing Cognito JWT for AppSync USER_POOLS auth. Pass opts.jwt.'
      );
    }
    // AppSync USER_POOLS expects the raw JWT in the Authorization header.
    headers['Authorization'] = jwt;
  }

  const res = await fetch(cfg.endpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify({ query, variables }),
    cache: 'no-store',
  });

  const json = (await res.json()) as {
    data?: T;
    errors?: GraphQLError[];
  };

  if (!res.ok) {
    throw new Error(`AppSync request failed: ${res.statusText}`);
  }

  if (json.errors?.length) {
    throw new Error(json.errors.map((e) => e.message).join(', '));
  }

  if (!json.data) {
    throw new Error('No data returned from AppSync');
  }

  return json.data;
}
