type GraphQLError = { message: string };

export type AppSyncAuthMode = 'apiKey' | 'userPools';

class AppSyncUnauthorizedError extends Error {
  status: number;

  constructor(status: number, message: string) {
    super(message);
    this.name = 'AppSyncUnauthorizedError';
    this.status = status;
  }
}

async function readJwtFromCookies(): Promise<string | null> {
  try {
    // Only available in Next.js server runtime.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { cookies } = require('next/headers') as typeof import('next/headers');
    const store = await cookies();
    return store.get('apsAdminJwt')?.value ?? null;
  } catch {
    return null;
  }
}

function loadAppSyncConfigFromAwsExports(): {
  endpoint: string;
  apiKey: string;
} | null {
  try {
    // Avoid importing aws-exports (can confuse bundlers); just parse it.
    // File is generated by Amplify and contains the AppSync endpoint + API key.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('fs') as typeof import('fs');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require('path') as typeof import('path');

    const awsExportsPath = path.join(process.cwd(), 'src', 'aws-exports.js');
    if (!fs.existsSync(awsExportsPath)) return null;

    const contents = fs.readFileSync(awsExportsPath, 'utf8');

    const endpointMatch = contents.match(
      /"aws_appsync_graphqlEndpoint"\s*:\s*"([^"]+)"/
    );
    const apiKeyMatch = contents.match(/"aws_appsync_apiKey"\s*:\s*"([^"]+)"/);

    const endpoint = endpointMatch?.[1];
    const apiKey = apiKeyMatch?.[1];

    if (!endpoint || !apiKey) return null;
    return { endpoint, apiKey };
  } catch {
    return null;
  }
}

function getAppSyncConfig(): { endpoint: string; apiKey: string } | null {
  const endpoint =
    process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT ||
    process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT;
  const apiKey =
    process.env.AWS_APPSYNC_API_KEY ||
    process.env.NEXT_PUBLIC_AWS_APPSYNC_API_KEY;

  if (endpoint && apiKey) return { endpoint, apiKey };
  return loadAppSyncConfigFromAwsExports();
}

/**
 * Small helper to talk to the AppSync API using the generated endpoint + API key.
 * Kept server-side only by importing it from server components/actions.
 */
export async function requestGraphQL<T>(
  query: string,
  variables?: Record<string, unknown>,
  opts?: { authMode?: AppSyncAuthMode; jwt?: string }
): Promise<T> {
  const cfg = getAppSyncConfig();
  const jwtFromCookie = await readJwtFromCookies();
  const authMode: AppSyncAuthMode =
    opts?.authMode ?? (jwtFromCookie ? 'userPools' : 'apiKey');

  // #region agent log (debug)
  fetch('http://127.0.0.1:7243/ingest/8e54769f-f43d-46b6-abd8-6d9007eecefc', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sessionId: 'debug-session',
      runId: 'pre-fix',
      hypothesisId: 'A',
      location: 'lib/appsync.ts:requestGraphQL:entry',
      message: 'requestGraphQL entry',
      data: {
        authMode,
        hasVars: !!variables,
        endpointHost: cfg?.endpoint ? new URL(cfg.endpoint).host : null,
        hasApiKey: !!cfg?.apiKey,
        hasJwt: !!opts?.jwt,
      },
      timestamp: Date.now(),
    }),
  }).catch(() => {});
  // #endregion agent log (debug)

  if (!cfg?.endpoint) {
    throw new Error(
      'Missing AppSync configuration. Set AWS_APPSYNC_GRAPHQL_ENDPOINT (or NEXT_PUBLIC_* equivalents), or ensure src/aws-exports.js exists.'
    );
  }

  const headers: Record<string, string> = {
    'content-type': 'application/json',
  };

  if (authMode === 'apiKey') {
    if (!cfg.apiKey) {
      throw new Error(
        'Missing AppSync API key. Set AWS_APPSYNC_API_KEY (or NEXT_PUBLIC_* equivalents), or ensure src/aws-exports.js exists.'
      );
    }
    headers['x-api-key'] = cfg.apiKey;
  } else {
    const jwt = opts?.jwt ?? jwtFromCookie;
    if (!jwt) {
      throw new Error(
        'Missing Cognito JWT for AppSync USER_POOLS auth. Pass opts.jwt.'
      );
    }
    // AppSync USER_POOLS expects the raw JWT in the Authorization header.
    headers['Authorization'] = jwt;
  }

  // #region agent log (debug)
  fetch('http://127.0.0.1:7243/ingest/8e54769f-f43d-46b6-abd8-6d9007eecefc', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sessionId: 'debug-session',
      runId: 'pre-fix',
      hypothesisId: 'D',
      location: 'lib/appsync.ts:requestGraphQL:headers',
      message: 'requestGraphQL prepared headers',
      data: {
        authMode,
        hasApiKeyHeader: typeof headers['x-api-key'] === 'string',
        hasAuthorizationHeader: typeof headers['Authorization'] === 'string',
      },
      timestamp: Date.now(),
    }),
  }).catch(() => {});
  // #endregion agent log (debug)

  const res = await fetch(cfg.endpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify({ query, variables }),
    cache: 'no-store',
  });

  const json = (await res.json()) as {
    data?: T;
    errors?: GraphQLError[];
  };

  // #region agent log (debug)
  fetch('http://127.0.0.1:7243/ingest/8e54769f-f43d-46b6-abd8-6d9007eecefc', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sessionId: 'debug-session',
      runId: 'pre-fix',
      hypothesisId: 'B',
      location: 'lib/appsync.ts:requestGraphQL:response',
      message: 'requestGraphQL response received',
      data: {
        status: res.status,
        ok: res.ok,
        errorCount: json.errors?.length ?? 0,
        errorMessages: (json.errors ?? []).map((e) => e.message).slice(0, 5),
      },
      timestamp: Date.now(),
    }),
  }).catch(() => {});
  // #endregion agent log (debug)

  if (res.status === 401 || res.status === 403) {
    throw new AppSyncUnauthorizedError(
      res.status,
      'AppSync request unauthorized'
    );
  }

  if (!res.ok) {
    throw new Error(`AppSync request failed: ${res.statusText}`);
  }

  if (json.errors?.length) {
    const unauthorized = json.errors.some((e) =>
      e.message.toLowerCase().includes('unauthorized')
    );
    if (unauthorized) {
      throw new AppSyncUnauthorizedError(
        res.status || 401,
        'AppSync request unauthorized'
      );
    }
    throw new Error(json.errors.map((e) => e.message).join(', '));
  }

  if (!json.data) {
    throw new Error('No data returned from AppSync');
  }

  return json.data;
}
